export enum ErrorCode {
  SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
  CANNOT_PARSE_REQUEST_BODY = 'CANNOT_PARSE_REQUEST_BODY',
  INVALID_DATA_VALIDATION = 'INVALID_DATA_VALIDATION',
  CANNOT_CREATE_REQUEST_TOKEN = 'CANNOT_CREATE_REQUEST_TOKEN',
  CANNOT_CREATE_SESSION_WITH_LOGIN = 'CANNOT_CREATE_SESSION_WITH_LOGIN',
  CANNOT_CREATE_SESSION = 'CANNOT_CREATE_SESSION',
  CANNOT_GET_FAVORITE_MOVIES = 'CANNOT_GET_FAVORITE_MOVIES',
  CANNOT_ADD_FAVORITE_MOVIE = 'CANNOT_ADD_FAVORITE_MOVIE',
  CANNOT_DELETE_FAVORITE_MOVIE = 'CANNOT_DELETE_FAVORITE_MOVIE',
}
