import { APP_CONFIG } from '@/configs/app';
import { cn } from '@/functions/cn';
import '@/styles/index.css';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReactNode } from 'react';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const Providers = ({ children }: { children: ReactNode }) => {
  return <NextIntlClientProvider>{children}</NextIntlClientProvider>;
};

export const metadata: Metadata = {
  title: {
    default: APP_CONFIG.name,
    template: `%s | ${APP_CONFIG.name}`,
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      className={cn(
        geistSans.variable,
        geistMono.variable,
        geistSans.className,
        'scheme-dark text-text bg-background antialiased',
      )}
      lang='en'
    >
      <body className={cn('overflow-x-hidden min-h-screen')}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
